In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("readyToModel.csv").drop(columns=['Unnamed: 0'])

In [3]:
df

,Company,TypeName,Ram,Weight,Price,Touchscreen,Ips,ppi,Cpu brand,HDD,SSD,Gpu brand,os
0,Apple,Ultrabook,8,1.37,71378.6832,0,1,226.983005,Intel Core i5,0,128,Intel,Mac
1,Apple,Ultrabook,8,1.34,47895.5232,0,0,127.677940,Intel Core i5,0,0,Intel,Mac
2,HP,Notebook,8,1.86,30636.0000,0,0,141.211998,Intel Core i5,0,256,Intel,Others/No OS/Linux
3,Apple,Ultrabook,16,1.83,135195.3360,0,1,220.534624,Intel Core i7,0,512,AMD,Mac
4,Apple,Ultrabook,8,1.37,96095.8080,0,1,226.983005,Intel Core i5,0,256,Intel,Mac
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1297,Lenovo,2 in 1 Convertible,4,1.80,33992.6400,1,1,157.350512,Intel Core i7,0,128,Intel,Windows
1298,Lenovo,2 in 1 Convertible,16,1.30,79866.7200,1,1,276.053530,Intel Core i7,0,512,Intel,Windows
1299,Lenovo,Notebook,2,1.50,12201.1200,0,0,111.935204,Other Intel Processor,0,0,Intel,Windows
1300,HP,Notebook,6,2.19,40705.9200,0,0,100.454670,Intel Core i7,1000,0,AMD,Windows
1301,Asus,Notebook,4,2.20,19660.3200,0,0,100.454670,Other Intel Processor,500,0,Intel,Windows

In [4]:
X = df.drop(columns=['Price'])
y = np.log(df['Price'])

In [5]:
y

0       11.175755
1       10.776777
2       10.329931
3       11.814476
4       11.473101
          ...
1297    10.433899
1298    11.288115
1299     9.409283
1300    10.614129
1301     9.886358
Name: Price, Length: 1302, dtype: float64

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.15,random_state=2)

In [8]:
X_train

,Company,TypeName,Ram,Weight,Touchscreen,Ips,ppi,Cpu brand,HDD,SSD,Gpu brand,os
183,Toshiba,Notebook,8,2.00,0,0,100.454670,Intel Core i5,0,128,Intel,Windows
1141,MSI,Gaming,8,2.40,0,0,141.211998,Intel Core i7,1000,128,Nvidia,Windows
1049,Asus,Netbook,4,1.20,0,0,135.094211,Other Intel Processor,0,0,Intel,Others/No OS/Linux
1020,Dell,2 in 1 Convertible,4,2.08,1,1,141.211998,Intel Core i3,1000,0,Intel,Windows
878,Dell,Notebook,4,2.18,0,0,141.211998,Intel Core i5,1000,128,Nvidia,Windows
...,...,...,...,...,...,...,...,...,...,...,...,...
466,Acer,Notebook,4,2.20,0,0,100.454670,Intel Core i3,500,0,Nvidia,Windows
299,Asus,Ultrabook,16,1.63,0,0,141.211998,Intel Core i7,0,512,Nvidia,Windows
493,Acer,Notebook,8,2.20,0,0,100.454670,AMD Processor,1000,0,AMD,Windows
527,Lenovo,Notebook,8,2.20,0,0,100.454670,Intel Core i3,2000,0,Nvidia,Others/No OS/Linux
1192,Apple,Ultrabook,8,0.92,0,1,226.415547,Other Intel Processor,0,0,Intel,Mac

In [9]:
X_test

,Company,TypeName,Ram,Weight,Touchscreen,Ips,ppi,Cpu brand,HDD,SSD,Gpu brand,os
248,HP,Notebook,4,1.49,0,1,165.632118,Intel Core i5,500,0,Intel,Windows
555,Asus,Notebook,4,2.00,0,0,100.454670,Other Intel Processor,500,0,Intel,Others/No OS/Linux
1250,HP,Notebook,4,1.86,0,0,100.454670,AMD Processor,500,0,AMD,Windows
547,Lenovo,Notebook,4,2.15,0,0,141.211998,Intel Core i5,1000,0,Intel,Others/No OS/Linux
885,HP,2 in 1 Convertible,4,1.28,1,0,165.632118,Intel Core i5,0,256,Intel,Windows
...,...,...,...,...,...,...,...,...,...,...,...,...
1129,HP,Gaming,8,3.35,0,1,127.335675,Intel Core i5,1000,128,Nvidia,Windows
172,Lenovo,Notebook,4,2.20,0,0,100.454670,AMD Processor,500,0,AMD,Others/No OS/Linux
322,Asus,Notebook,8,2.00,0,0,157.350512,Intel Core i7,0,256,Intel,Windows
996,HP,Ultrabook,8,1.11,1,1,165.632118,Intel Core i7,0,256,Intel,Windows
470,HP,2 in 1 Convertible,8,1.29,1,1,331.264236,Intel Core i7,0,512,Intel,Windows

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

In [15]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1106 entries, 183 to 1192
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Company      1106 non-null   object
 1   TypeName     1106 non-null   object
 2   Ram          1106 non-null   int64
 3   Weight       1106 non-null   float64
 4   Touchscreen  1106 non-null   int64
 5   Ips          1106 non-null   int64
 6   ppi          1106 non-null   float64
 7   Cpu brand    1106 non-null   object
 8   HDD          1106 non-null   int64
 9   SSD          1106 non-null   int64
 10  Gpu brand    1106 non-null   object
 11  os           1106 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 112.3+ KB

In [25]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor

In [27]:
# Using linear regression

step1 = ColumnTransformer(transformers=[
    ('col_tnf', OneHotEncoder(sparse=False,drop='first'),[0,1,7,10,11])
], remainder='passthrough')

step2 = LinearRegression() 

pipe = Pipeline([
    ('step1',step1),
    ('step2',step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

In [28]:
from sklearn.metrics import r2_score, mean_absolute_error

In [29]:
print("R2 score", r2_score(y_test,y_pred))

R2 score 0.8073277450155087

In [30]:
print("MAE",mean_absolute_error(y_test,y_pred))

MAE 0.21017827953019158

In [33]:
# using KNN

step1 = ColumnTransformer(transformers=[
    ('col_tnf', OneHotEncoder(sparse=False,drop='first'),[0,1,7,10,11])
], remainder='passthrough')

step2 = KNeighborsRegressor(n_neighbors=3)

pipe = Pipeline([
    ('step1',step1),
    ('step2', step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

print("R2 score", r2_score(y_test,y_pred))

print("MAE",mean_absolute_error(y_test,y_pred))

R2 score 0.8031008164264897
MAE 0.19268746498695286

In [35]:
# Using Decision tree

step1 = ColumnTransformer(transformers=[
    ('col_tnf', OneHotEncoder(sparse=False,drop='first'),[0,1,7,10,11])
], remainder='passthrough')

step2 = DecisionTreeRegressor(max_depth=8)

pipe = Pipeline([
    ('step1',step1),
    ('step2',step2)
])

pipe.fit(X_train,y_train)

y_pred = pipe.predict(X_test)

print("R2 score", r2_score(y_test,y_pred))

print("MAE",mean_absolute_error(y_test,y_pred))

R2 score 0.8386651244694967
MAE 0.1828686847930586

In [ ]:
import pickle 

pickle.dump(df,open('df.pkl','wb'))
pickle.dump(pipe,)